version: "3.4"
services:
  beacon-chain:
    image: "beacon-chain.prysm.dnp.dappnode.eth:1.0.0"
    build:
      context: beacon-chain
      args:
        UPSTREAM_VERSION: v2.1.3
    volumes:
      - "beacon-chain-data:/data"
    ports:
      - "13000"
      - 12000/udp
    restart: unless-stopped
    environment:
      HTTP_WEB3PROVIDER: "http://geth.dappnode:8545"
      CHECKPOINT_SYNC_URL: ""
      CORSDOMAIN: "http://prysm.dappnode"
      WEB3_BACKUP: ""
      EXTRA_OPTS: ""
  validator:
    image: "validator.prysm.dnp.dappnode.eth:1.0.0"
    build:
      context: validator
      args:
        UPSTREAM_VERSION: v2.1.3
    volumes:
      - "validator-data:/root/"
    restart: unless-stopped
    environment:
      LOG_TYPE: INFO
      BEACON_RPC_PROVIDER: "beacon-chain.prysm.dappnode:4000"
      BEACON_RPC_GATEWAY_PROVIDER: "beacon-chain.prysm.dappnode:3500"
      GRAFFITI: validating_from_DAppNode
      EXTRA_OPTS: ""
      FEE_RECIPIENT_ADDRESS: ""
volumes:
  beacon-chain-data: {}
  validator-data: {}
