version: "3.4"
services:
  beacon-chain:
    image: "beacon-chain.prysm.dnp.dappnode.eth:1.0.0"
    build:
      context: beacon-chain
      args:
        UPSTREAM_VERSION: v2.1.4
    volumes:
      - "beacon-chain-data:/data"
    ports:
      - "13103:13103/tcp"
      - "12103:12103/udp"
    restart: unless-stopped
    environment:
      HTTP_WEB3PROVIDER: "http://geth.dappnode:8545"
      CORSDOMAIN: "http://prysm.dappnode"
      P2P_TCP_PORT: 13103
      P2P_UDP_PORT: 12103
      EXTRA_OPTS: ""
  validator:
    image: "validator.prysm.dnp.dappnode.eth:1.0.0"
    build:
      context: validator
      args:
        UPSTREAM_VERSION: v2.1.4
    volumes:
      - "validator-data:/root/"
    restart: unless-stopped
    environment:
      BEACON_RPC_PROVIDER: "beacon-chain.prysm.dappnode:4000"
      BEACON_RPC_GATEWAY_PROVIDER: "beacon-chain.prysm.dappnode:3500"
      GRAFFITI: validating_from_DAppNode
      EXTRA_OPTS: ""
volumes:
  beacon-chain-data: {}
  validator-data: {}
